### ISSUE TITLE
Support built-in search on the website

### ISSUE THREAD

**Issue by FeynmanZhou** [deislabs/ratify-web#27]
We need to support searching content including docs and blogs on the Ratify website so that users can easily find their expected content by searching keywords. 

Algolia provides free search program for open source projects. We can apply for that program and integrate Algolia search on the website: https://www.algolia.com/for-open-source/

**Comment by sahilshityalkar** [comment]
Subject: Interest in Algolia Search Integration

Dear FeynmanZhou,

I'm enthusiastic about integrating Algolia search for the Ratify website. i am eager to contribute to this project. Looking forward to the opportunity.**Can you guide me or provide more information about the task**?

Best regards,
sahil shityalkar

**Comment by FeynmanZhou** [comment]
@sahilshityalkar Thanks for your interest! I would like to add the Algolia search on the Ratify website, such as we did for [oras website](https://oras.land/).

I can apply for the free search program on Algolia platform and share the application ID and embed code with you. So that you can implement it in this repo by raising a PR.

**Comment by FeynmanZhou** [comment]
@sahilshityalkar  Would you be willing to take it? If so, you could comment on it. We could assign this issue to you.

**Comment by ShravaniAK** [comment]
Hey @FeynmanZhou , I would like to take up this issue

**Comment by FeynmanZhou** [comment]
@ShravaniAK It's glad to hear your willingness. Welcome back. 
I could assign this issue to you.

**Comment by ShravaniAK** [comment]
yeah please assign it to me , and also it would be nice if you share the application id and key to be added in the code.

**Comment by FeynmanZhou** [comment]
@ShravaniAK Sure. I will apply for the program on https://www.algolia.com/for-open-source/ and provide the application id/key to you this week.

**Comment by FeynmanZhou** [comment]
I've shared the app id/key with @ShravaniAK in the slack

**Comment by susanshi** [comment]
thanks so much for the contribution @FeynmanZhou and @ShravaniAK. Having search capability is a huge improvement! The change has been delpoyed, should be close this issue too?

**Comment by FeynmanZhou** [comment]
@susanshi We can close it now.
